# Generated by Django 4.0.4 on 2022-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
